services:
  airflow-postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    networks:
      - common_net

  airflow-init:
    build: .
    container_name: airflow_init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__BASE_LOG_FOLDER: /opt/airflow/logs
    volumes:
      - ./airflow:/opt/airflow
      - ./requirements.txt:/opt/airflow/requirements.txt

    entrypoint: >
      bash -c "
        echo 'Waiting for Postgres...'
        until airflow db check; do
          sleep 2
        done
        mkdir -p /opt/airflow/dags /opt/airflow/logs /opt/airflow/plugins
        chown -R airflow: /opt/airflow
        airflow db init
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "
    networks:
      - common_net

  airflow-webserver:
    build: .
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__BASE_LOG_FOLDER: /opt/airflow/logs
    volumes:
      - ./airflow:/opt/airflow
      - ./requirements.txt:/opt/airflow/requirements.txt

    command: webserver
    ports:
      - "8081:8080"
    networks:
      - common_net

  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__BASE_LOG_FOLDER: /opt/airflow/logs
    volumes:
      - ./airflow:/opt/airflow
      - ./requirements.txt:/opt/airflow/requirements.txt
    networks:
      - common_net
    
    command: scheduler
    

volumes:
  airflow_postgres_data:

networks:
  common_net:
    external: true

