services:
  airflow-postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_net

  airflow-init:
    image: apache/airflow:2.9.1-python3.11
    container_name: airflow_init
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    entrypoint: >
      bash -c "airflow db migrate && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"
    networks:
      - airflow_net

  airflow-webserver:
    image: apache/airflow:2.9.1-python3.11
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: webserver
    networks:
      - airflow_net

  airflow-scheduler:
    image: apache/airflow:2.9.1-python3.11
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: scheduler
    networks:
      - airflow_net

volumes:
  airflow_postgres_data:

networks:
  airflow_net:
    driver: bridge
