services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: transact_crypto_db
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse
      - ./clickhouse_config:/etc/clickhouse-server

  clickhouse-client:
    image: clickhouse/clickhouse-client:24.3
    container_name: clickhouse-client
    depends_on:
      - clickhouse
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 5 && clickhouse-client --host clickhouse --port 9000 --user admin --password admin123
