  grafana:
    image: grafana/grafana:10.0.1
    container_name: grafana
    depends_on:
      - ksqldb-server
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
