services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"       # S3 API
      - "9001:9001"       # Web UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

volumes:
  minio_data: