services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  volumes:
    pgdata:
