CREATE TABLE ohlc_5m AS
SELECT
  instId,
  WINDOWSTART AS ws,
  MAX(px) AS high,
  MIN(px) AS low,
  EARLIEST_BY_OFFSET(px) AS open,
  LATEST_BY_OFFSET(px) AS close,
  SUM(sz) AS volume
FROM trades_stream
WINDOW HOPPING (SIZE 5 MINUTES, ADVANCE BY 1 SECOND)
GROUP BY instId
EMIT CHANGES;
